version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "7000:7000"
    depends_on:
      - order-database
    networks:
      - orders_network
    environment:
      - MONGO_URI=mongodb://root:example@order-database:27017/
      - MONGO_DB=orders

  order-database:
    image: mongo:latest
    container_name: order-database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"
    networks:
      - orders_network
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  orders_network:
    driver: bridge
